FROM ubuntu:16.04

RUN apt-get -q update && apt-get -y install \
      build-essential \
      rsync \
      python \
      unzip \
      wget \
      bc \
      cpio \
      libc6-i386 \
      libbz2-dev
