#!/bin/sh

set -e -u -x

IMAGE_ROOT="$PWD/image-root"
BUILDROOT_SRC="$PWD/buildroot"

mkdir -p /sys/fs/cgroup
mountpoint -q /sys/fs/cgroup || \
  mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup

for d in `sed -e '1d;s/\([^\t]\)\t.*$/\1/' /proc/cgroups`; do
  mkdir -p /sys/fs/cgroup/$d
  mountpoint -q /sys/fs/cgroup/$d || \
    mount -n -t cgroup -o $d cgroup /sys/fs/cgroup/$d
done

docker daemon -g /tmp/build/graph &

until docker info >/dev/null 2>&1; do
  echo waiting for docker to come up...
  sleep 1
done

docker load -i ./buildroot-tarmaker-image/image

docker tag \
  $(docker images -q) \
  $(cat buildroot-tarmaker-image/repository):$(cat buildroot-tarmaker-image/tag)

docker images

cd buildroot-images

cp -a ./${FLAVOR}/* ${IMAGE_ROOT}

cp -a "$BUILDROOT_SRC" ./${FLAVOR}/tarmaker/buildroot

docker build -t tarmaker $FLAVOR/tarmaker
docker run --name builder tarmaker
docker cp builder:/tmp/rootfs.tar "$IMAGE_ROOT"
docker cp builder:/tmp/rootfs.tar.md5 "$IMAGE_ROOT"

chown 1000:1000 "$IMAGE_ROOT"/rootfs*

docker rm -f builder
docker rmi tarmaker
